FULL_NAME = 'full_name'
SHORT_NAME = 'short_name'
AUTHOR = 'author'
TITLE_INDEX = 'title_index'
TITLE_CONTENT = 'title_content'
CONTENT = 'content'
LAST_CHAPTER = 'last_chapter'
CHAPTER_INDEX = 'chapter_index'
